//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Accnum { get; set; }
        public string Accountid { get; set; }
        public string AccountType { get; set; }
    }
}
