//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.FixedDepositAccounts = new HashSet<FixedDepositAccount>();
            this.LoanAccounts = new HashSet<LoanAccount>();
            this.SavingsAccounts = new HashSet<SavingsAccount>();
        }
        
        public int CustNum { get; set; }
        public string CustID { get; set; }

        [Required]
        [StringLength(15, MinimumLength = 8)]
        public string Cpassword { get; set; }

        [Required]
        public string CustName { get; set; }
        public System.DateTime DOB { get; set; }

        [Required]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "PAN must be 8 characters.")]
        [RegularExpression(@"^[A-Za-z]{4}\d{4}$", ErrorMessage = "PAN must start with 4 letters followed by 4 digits.")]
        [Display(Name = "PAN")]
        public string PAN { get; set; }

        [Required]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Number must be 10 characters.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone Number should contain only digits.")]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedDepositAccount> FixedDepositAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanAccount> LoanAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavingsAccount> SavingsAccounts { get; set; }
    }
}
