//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int Empnum { get; set; }
        public string Epassword { get; set; }
        public string Empid { get; set; }
        public string Empname { get; set; }
        public string Deptid { get; set; }
        public string Emptype { get; set; }
        public string PAN { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
